import json
import zipfile
import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

def export_json(data: dict, output_path: str):
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

def export_markdown(data: dict, output_path: str):
    with open(output_path, 'w', encoding='utf-8') as f:
        for key, value in data.items():
            f.write(f"# {key.replace('_', ' ').title()}\n\n")
            if isinstance(value, str):
                f.write(f"{value}\n\n")
            elif isinstance(value, list):
                for item in value:
                    f.write(f"- {item}\n")
                f.write("\n")
            elif isinstance(value, dict):
                for subkey, subvalue in value.items():
                    f.write(f"**{subkey}**: {subvalue}\n\n")

def export_txt(data: dict, output_path: str):
    with open(output_path, 'w', encoding='utf-8') as f:
        for key, value in data.items():
            f.write(f"--- {key.replace('_', ' ').title()} ---\n\n")
            if isinstance(value, str):
                f.write(f"{value}\n\n")
            elif isinstance(value, list):
                for item in value:
                    f.write(f"* {item}\n")
                f.write("\n")
            elif isinstance(value, dict):
                for subkey, subvalue in value.items():
                    f.write(f"{subkey}: {subvalue}\n\n")

def export_pdf(data: dict, output_path: str):
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=1
    )
    heading_style = styles['Heading2']
    normal_style = styles['Normal']
    
    story = []
    
    selected_title = data.get("selected_title", "Podcast Episode Report")
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(selected_title, title_style))
    story.append(Spacer(1, 1 * inch))
    story.append(Paragraph("Generated by Podcast Producer Agent", styles['Normal']))
    story.append(PageBreak())
    
    keys_to_include = ['executive_summary', 'show_notes', 'key_takeaways', 'chapter_timestamps', 'highlights', 'social_media', 'seo_tags']
    
    for key in keys_to_include:
        if key in data and data[key]:
            story.append(Paragraph(key.replace('_', ' ').title(), heading_style))
            story.append(Spacer(1, 0.2 * inch))
            
            value = data[key]
            if isinstance(value, str):
                text = value.replace('\n', '<br/>')
                story.append(Paragraph(text, normal_style))
            elif isinstance(value, list):
                for item in value:
                    text = str(item).replace('\n', '<br/>')
                    story.append(Paragraph(f"• {text}", normal_style))
            elif isinstance(value, dict):
                for subkey, subvalue in value.items():
                    text = f"<b>{subkey}:</b> {subvalue}".replace('\n', '<br/>')
                    story.append(Paragraph(text, normal_style))
            
            story.append(Spacer(1, 0.4 * inch))
            
    doc.build(story)

def create_zip_package(files_to_zip: list, output_zip_path: str):
    with zipfile.ZipFile(output_zip_path, 'w') as zipf:
        for file in files_to_zip:
            if os.path.exists(file):
                zipf.write(file, os.path.basename(file))
